export const AUDIO_LIST_REQUEST = 'AUDIO_LIST_REQUEST'
export const AUDIO_LIST_SUCCESS = 'AUDIO_LIST_SUCCESS'
export const AUDIO_LIST_FAIL = 'AUDIO_LIST_FAIL'

export const AUDIO_DETAILS_REQUEST = 'AUDIO_DETAILS_REQUEST'
export const AUDIO_DETAILS_SUCCESS = 'AUDIO_DETAILS_SUCCESS'
export const AUDIO_DETAILS_FAIL = 'AUDIO_DETAILS_FAIL'

export const AUDIO_DELETE_REQUEST = 'AUDIO_DELETE_REQUEST'
export const AUDIO_DELETE_SUCCESS = 'AUDIO_DELETE_SUCCESS'
export const AUDIO_DELETE_FAIL = 'AUDIO_DELETE_FAIL'

export const AUDIO_CREATE_REQUEST = 'AUDIO_CREATE_REQUEST'
export const AUDIO_CREATE_SUCCESS = 'AUDIO_CREATE_SUCCESS'
export const AUDIO_CREATE_FAIL = 'AUDIO_CREATE_FAIL'
export const AUDIO_CREATE_RESET = 'AUDIO_CREATE_RESET'

export const AUDIO_UPDATE_REQUEST = 'AUDIO_UPDATE_REQUEST'
export const AUDIO_UPDATE_SUCCESS = 'AUDIO_UPDATE_SUCCESS'
export const AUDIO_UPDATE_FAIL = 'AUDIO_UPDATE_FAIL'
export const AUDIO_UPDATE_RESET = 'AUDIO_UPDATE_RESET'
