export const SEND_CONTACT_FORM_REQUEST = 'SEND_CONTACT_FORM_REQUEST'
export const SEND_CONTACT_FORM_SUCCESS = 'SEND_CONTACT_FORM_SUCCESS'
export const SEND_CONTACT_FORM_FAIL = 'SEND_CONTACT_FORM_FAIL'
